# Generated by Django 6.0 on 2026-01-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaenfermeria',
            options={},
        ),
        migrations.RenameField(
            model_name='notaenfermeria',
            old_name='contenido',
            new_name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='adjunto',
            name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='adjunto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='cambio_panal',
            field=models.CharField(default='No aplica', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='escala_dolor',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='evolucion',
            field=models.CharField(choices=[('1', 'Evolución 1'), ('2', 'Evolución 2'), ('3', 'Evolución 3'), ('4', 'Evolución 4'), ('5', 'Evolución 5'), ('6', 'Evolución 6'), ('X', 'Evolución extraordinaria')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='frecuencia_cardiaca',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='frecuencia_respiratoria',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='glasgow',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='posicion_paciente',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='procedimientos',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='saturacion_oxigeno',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaenfermeria',
            name='tension_arterial',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notaenfermeria',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.CharField(max_length=50),
        ),
    ]
